### ISSUE TITLE
Running jb install with a parent directy argument overwrites current directory with a symlink

### ISSUE THREAD

**Issue by wendtek** [jsonnet-bundler/jsonnet-bundler#101]
### Issue
Running something akin to `jb install ..` results in a panic and creates a symbolic link replacing the current directory.

After seeing this behavior on my own laptop accidentally and losing work, I recreated in a container.
```
root@39fb74781237:/# mkdir -p /test1/test2
root@39fb74781237:/# ls -l /test1
total 4
drwxr-xr-x 2 root root 4096 May  1 15:36 test2
root@39fb74781237:/# cd /test1/test2
root@39fb74781237:/test1/test2# jb init && jb install ..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x76e95d]

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/pkg.cleanLegacySymlinks.func1(0x8374e0, 0x6, 0x0, 0x0, 0x8c5380, 0xc000118480, 0x1, 0xc0001182d0)
	/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/packages.go:136 +0x5d
path/filepath.Walk(0x8374e0, 0x6, 0xc00019f810, 0x1, 0xc00019fa18)
	/usr/local/go/src/path/filepath/path.go:404 +0x6a
github.com/jsonnet-bundler/jsonnet-bundler/pkg.cleanLegacySymlinks(0x8374e0, 0x6, 0xc0001182d0, 0x0, 0x0)
	/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/packages.go:131 +0x2c2
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure(0xc0001180c0, 0xc000118101, 0x8374e0, 0x6, 0xc000118120, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/pkg/packages.go:94 +0x20b
main.installCommand(0xc000018004, 0xc, 0x8374e0, 0x6, 0xc000098f00, 0x1, 0x1, 0x0)
	/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/install.go:71 +0x68b
main.Main(0xc00008e058)
	/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/main.go:77 +0x82b
main.main()
	/go/pkg/mod/github.com/jsonnet-bundler/jsonnet-bundler@v0.3.1/cmd/jb/main.go:34 +0x22
root@39fb74781237:/test1/test2# ls -l /test1
total 0
lrwxrwxrwx 1 root root 6 May  1 15:36 test2 -> /test1
```

### Steps to reproduce
From any directory with a valid `jsonnetfile.json`, run `jb install ../`

### Expected behavior
I would expect the tool to either identify that it is about to make a recursive symlink loop while traversing dependencies and throw an error or break the loop so it is not traversed more than once.

Having a warning any time files/directories are going to be overwritten would also mitigate accidental loss of files when a user mistakenly enters a parent directory as an argument. Possibly also satisfies: https://github.com/jsonnet-bundler/jsonnet-bundler/issues/97

I suspect some sort of cyclical dependency handling may also need to be done in the case where a user makes two packages depend on one another and run a `jb update` in either.

**Comment by rollandf** [comment]
It is fixed on master by #100 and #103
