### ISSUE TITLE
jb-linux-amd64 v0.4.0 is v0.2.0

### ISSUE THREAD

**Issue by ebengt** [jsonnet-bundler/jsonnet-bundler#108]
After download of jb-linux-amd64 from https://github.com/jsonnet-bundler/jsonnet-bundler/releases/tag/v0.4.0
I get:
 ./jb-linux-amd64 --version
v0.2.0-41-g447344d

Does anybody get v0.4.0... ?

**Comment by sh0rez** [comment]
This is most likely related to the binary artifacts being built before the repo was tagged locally.

I rebuilt and replaced the artifacts, should be fixed now.
