### ISSUE TITLE
When cloning, are git submodules fetched?

### ISSUE THREAD

**Issue by ghostsquad** [jsonnet-bundler/jsonnet-bundler#113]
When cloning, are git submodules fetched?

**Comment by c0ffeec0der** [comment]
It looks like when "subdir" is defined. The contents of root and subdir are not cloned.

try instructions on https://github.com/coreos/kube-prometheus

$ mkdir my-kube-prometheus; cd my-kube-prometheus
$ jb init  
$ jb install github.com/coreos/kube-prometheus/jsonnet/kube-prometheus@release-0.4

Check folder vendor contents. Most are empty

**Comment by metalmatze** [comment]
Unless there's a reason for us to implement support for submodules, I'm closing this for now. Feel free to re-open in the future.
