### ISSUE TITLE
Feature request: quiet option

### ISSUE THREAD

**Issue by hangxie** [jsonnet-bundler/jsonnet-bundler#123]
Like `-q`/`-s` to eliminate those progress bars, I think all we need to know is `remote: Total 40 (delta 7), reused 40 (delta 7), pack-reused 0` as a summary if possible, or that can be gone if it's hard to achieve.

Background - our CI builds 12 components in one job, jsonnet-bundler populated these lines that dominated the output and make it hard for people to read actual build messages:
```
remote: Compressing objects:  88% (235/266)           
...
Receiving objects:  72% (979/1359)
...
Unpacking objects:  32% (13/40)
```

**Comment by metalmatze** [comment]
Sounds good, especially for CI. Happy to merge a PR for it :)
