### ISSUE TITLE
Error when referencing branch with '/' in name with jb install

### ISSUE THREAD

**Issue by hoenn** [jsonnet-bundler/jsonnet-bundler#135]
Using `/` in a branch name and using that for `version` in jsonnetfile.json will cause `jb install/update` to error. I renamed my remote branch and this error went away as expected. I've found it pretty common to name branches `user/whatever`, other users may run into this.

Steps to reproduce:
1. Create a branch with a `/` in the name on a remote repository
2. Add that repo and version as a dependency source in jsonnetfile.json
3.  `jb install`

Error
```
jb: error: failed to install packages: downloading: failed to create tmp dir: mkdir vendor/.tmp/jsonnetpkg-github.com-grafana-dnsmasq_exporter-dnsmasq-mixin-hoenn/quick-dashboard-fixes997989372: no such file or directory
```

**Comment by metalmatze** [comment]
Interesting. Yes, we should support slashes in branch names.

**Comment by Cicatrice** [comment]
Hello,

I notice this PR https://github.com/jsonnet-bundler/jsonnet-bundler/pull/110 actually fixed this bug by replacing the way `jb` generate the temporary path : https://github.com/jsonnet-bundler/jsonnet-bundler/commit/9e88f6d38d2c12ea86ea04ded932a106fa5df972#diff-5242cbabda12c6e180bb1acbfcc76f59021c7e83b80747ca20662cf92369c478R181

The main problem is that it has not been released yet on GitHub, and the only way to benefit from it is to use `go get` installation method, described in [README](https://github.com/jsonnet-bundler/jsonnet-bundler#install).

Is there a plan to publish a new release on GitHub soon?

**Comment by metalmatze** [comment]
Yep, we should. The last release is quite a while ago :smile:

**Comment by hoenn** [comment]
Since this is apparently fixed on master (thanks for pointing that out @Cicatrice) I'll close the issue.

**Comment by wiegandf** [comment]
@metalmatze any updates on a new release?
