### ISSUE TITLE
During `jb init`, store --jsonnetpkg-home flag in `jsonnetfile.json`; use this stored value to override default of "vendor"

### ISSUE THREAD

**Issue by darrenjaneczek** [jsonnet-bundler/jsonnet-bundler#143]
To prevent the jsonnetpkg-home default "vendor" clashing with the go package default "vendor," I decided to use the following command line flag to differentiate between the two.

```--jsonnetpkg-home="jbvendor"```

Every `jb` command that I run will have to use this flag, to prevent actions happening in the default "vendor" location. Would it be reasonable to have the specified directory be stored in the `jsonnetfile.json` such that subsequent `jb` commands in that location would automatically use that value instead of the default?

If so, would it then make sense for this flag to only be applied to the `init` command, and then allow the content of the file to decide, moving forward? The file could be updated manually to select a different location, or perhaps the `jb init` command (or another command) could be permitted to update the flag value.

Thanks.

**Comment by ghostsquad** [comment]
I believe this is a duplicate of #120

**Comment by darrenjaneczek** [comment]
> I believe this is a duplicate of #120

Agreed. Thanks.
