### ISSUE TITLE
golang has deprecated 'get'

### ISSUE THREAD

**Issue by JorundMartinsen** [jsonnet-bundler/jsonnet-bundler#148]
Update documentation to conform to latest golang version, using go install

With go v1.17
```
$ GO111MODULE="on" go get github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb

go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by KlavsKlavsen** [comment]
Same problem here - trying to find a diff. way to actually install jb :(

**Comment by paulfantom** [comment]
Feel free to create a PR with updated installation method. `go install -a github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb@latest` should work just fine for golang 1.17.

**Comment by KlavsKlavsen** [comment]
@paulfantom done ;)

**Comment by KlavsKlavsen** [comment]
(and done for gojsontoyaml too - which had same issue :)
