### ISSUE TITLE
Perform `git pull` instead of `git clone` on update

### ISSUE THREAD

**Issue by intelfx** [jsonnet-bundler/jsonnet-bundler#18]
Each subsequent invocation of `jb update` performs a complete `git clone` of all dependencies. This is suboptimal and works contrary to the Git's central idea. `jb` should be doing a pull instead.

**Comment by metalmatze** [comment]
The problem with the current implementation is, that it clones the repositories to `.tmp` and then copies the contents of a cloned repository to `vendor/`. This essentially throws away all git related files, once `.tmp` gets deleted. 
@tomwilkie has an open PR on using a cache #9.

**Comment by davidovich** [comment]
I think this can be closed with the latest enhancements in [v0.2.0](https://github.com/jsonnet-bundler/jsonnet-bundler/releases/tag/v0.2.0).

**Comment by sh0rez** [comment]
Only for GitHub, right? otherwise, we will still clone (sometimes only a shallow clone, sparse checkout, whatever, but still clone)

**Comment by sh0rez** [comment]
Closing this for now.

In reality, most packages are installed from GitHub using the http archive. Furthermore, `jb` does not keep the `.git` folder around in `vendor`, so pulling instead of cloning is not really an option.
