### ISSUE TITLE
`jb update` should be able to take a repo as argument

### ISSUE THREAD

**Issue by metalmatze** [jsonnet-bundler/jsonnet-bundler#19]
When running `jb update` we should be able to pass an argument to the CLI command with the specific repo we want to update. This will prevent all over dependencies to be updated every time `jb update` is run.

/cc @squat

**Comment by sh0rez** [comment]
This is possible now by using `jb install <package-name>` which installs the specified version of that package, effectively updating it .. Can this be close?
