### ISSUE TITLE
Dependencies on local directories

### ISSUE THREAD

**Issue by metalmatze** [jsonnet-bundler/jsonnet-bundler#20]
jb should better handle having dependencies on local directories.

Example:

https://github.com/coreos/prometheus-operator/blob/aa374c3f63914455673e8079b613fe8f55c440e2/contrib/kube-prometheus/jsonnetfile.json#L7-L8

Currently for this to work, one has to make a commit and only then jb is able to vendor the new commit as dependency.

**Comment by brancz** [comment]
Indeed, closed by #36.
