### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by gouthamve** [jsonnet-bundler/jsonnet-bundler#24]
I'm doing a training and it would be super useful to have ready made binaries for those that don't have go installed.

**Comment by metalmatze** [comment]
I wouldn't mind cutting a `v0.1.0`. I guess for now the most simple solution would be to just upload binaries from who ever builds them?

**Comment by brancz** [comment]
didn't see this, but happy to cut v0.1.0 from current master and upload artifacts "manually" for now

**Comment by metalmatze** [comment]
We have v0.1.0. https://github.com/jsonnet-bundler/jsonnet-bundler/releases/tag/v0.1.0
This is release was made especially for @gouthamve. Have fun. :smile:
