### ISSUE TITLE
jb init on existing project

### ISSUE THREAD

**Issue by metalmatze** [jsonnet-bundler/jsonnet-bundler#3]
Running `jb init` on existing project completely overrides the `jsonnetfile.json` with an empty one.

Should it just fail or rather ask for permission if the file already exists?

**Comment by brancz** [comment]
that behavior is the same as many other tools, but I agree that at least it should ask whether it should override an existing file

**Comment by janwillies** [comment]
The overwriting has been a huge problem with `helm create foo`, I would prefer a warning too
