### ISSUE TITLE
jsonnetfiles not updated when installing new bundles

### ISSUE THREAD

**Issue by glindstedt** [jsonnet-bundler/jsonnet-bundler#30]
## Steps to reproduce

```bash
jb init
jb install https://github.com/bitnami-labs/kube-libsonnet
jb install https://github.com/ksonnet/ksonnet-lib/ksonnet.beta.3
```

### Expected results

Both `jsonnetfile.json` and `jsonnetfile.lock.json` includes both bundles.

### Actual results

Only the first installed bundle is present in `jsonnetfile.json` and `jsonnetfile.lock.json`

### Version

Experienced using current master, commit 080f157c7fb85ad0281ea78f6c641eaa570a582f

**Comment by metalmatze** [comment]
Yes. I can confirm this. This is definitely a bug we should fix.
