### ISSUE TITLE
panic when executing `jb install`

### ISSUE THREAD

**Issue by paulfantom** [jsonnet-bundler/jsonnet-bundler#39]
I used `jb` from master branch (commit [c734431](https://github.com/jsonnet-bundler/jsonnet-bundler/commit/c734431ebd93240a3ab1ceb9a8fca61ec07181fe)) and got following error:
```
/home/paulfantom/.go/bin/jb install
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x582ad3]

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Install(0x6a6a20, 0xc0000ac018, 0x101, 0xc0000ae300, 0x15, 0xc00010a000, 0x9, 0x9, 0x65b705, 0x6, ...)
        /home/paulfantom/.go/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go:58 +0x353
main.installCommand(0x65b705, 0x6, 0x0, 0x0, 0x0, 0x7)
        /home/paulfantom/.go/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:295 +0xa5e
main.Main(0xc00008e058)
        /home/paulfantom/.go/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:93 +0x724
main.main()
        /home/paulfantom/.go/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:61 +0x22
make: *** [Makefile:35: vendor] Error 2
```

It doesn't happen when using release binary.

**Comment by metalmatze** [comment]
This will happen when you don't have the latest revision of jb and still try to use local dependencies. 
```
go get -u github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
```
Let me know if this persists afterwards.

**Comment by paulfantom** [comment]
```
go get -u github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb
```

That's what I did in the first place :)

**Comment by metalmatze** [comment]
interesting. So what `jsonnetfile.json` and `jsonnetfile.lock.json` caused this? How can we reproduce this?

**Comment by paulfantom** [comment]
That was at https://github.com/openshift/cluster-monitoring-operator/pull/456. But it was my mistake, I ran `go get -u github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb` while having go modules enabled and being in `github.com/openshift/cluster-monitoring-operator` directory :man_facepalming:

**Comment by metalmatze** [comment]
Glad it was nothing major then. :)
