### ISSUE TITLE
jsonnet.file.lock ordering should be stable and deterministic

### ISSUE THREAD

**Issue by bgagnon** [jsonnet-bundler/jsonnet-bundler#41]
This is necessary to keep sane diff and Git commit histories, and simplifies manual pinning of versions. A simple solution would be to alpha-sort the dependencies array before writing out the JSON file.

**Comment by metalmatze** [comment]
It should be stable in a way that it always iterates over the items in the `jsonnetfile.json` in the same order.

**Comment by bgagnon** [comment]
The problem is not so much the direct dependencies, but the transitive ones. This partially ordered set can vary over time. The current implementation causes thing to shift around any time a direct or indirect dependency is bumped.
