### ISSUE TITLE
Creating a new release?

### ISSUE THREAD

**Issue by nabadger** [jsonnet-bundler/jsonnet-bundler#45]
Would it be possible to have a new release? 

There's quite a few changes since v0.1.0 and pre-built binaries are really nice :)

Many thanks

**Comment by metalmatze** [comment]
I guess we could do another one. However I want to make sure that the latest changes with e-tags are stable. :)

**Comment by sh0rez** [comment]
For demos at upcoming conferences a release including binaries would be handy .. 

@metalmatze @brancz are you fine with me cutting a new one right now?

**Comment by sh0rez** [comment]
Release done
