### ISSUE TITLE
jb install: jsonnetfile.json should not be written if not modified

### ISSUE THREAD

**Issue by davidovich** [jsonnet-bundler/jsonnet-bundler#55]
Currently, jsonnetfile is [written unconditionally](https://github.com/jsonnet-bundler/jsonnet-bundler/blob/master/cmd/jb/install.go#L67-L72) at each install, even if no new dependencies were introduced (bare `jb install`).

This breaks some Makefile driven workflows as targets depending on `jsonnetfile.json` will always be out of date.

I can make a small PR to fix this if there is interest.

**Comment by sh0rez** [comment]
Duplicate of https://github.com/jsonnet-bundler/jsonnet-bundler/issues/11 actually 😛 

On my list of small fixes I wanted to do but happy to hand this off to you as well :D

**Comment by davidovich** [comment]
Ok, PR coming. I'll close as duplicate.
