### ISSUE TITLE
Lock file incorrectly built

### ISSUE THREAD

**Issue by brancz** [jsonnet-bundler/jsonnet-bundler#6]
Transitive dependencies are not correctly propagated to the lock file, only the original dependency currently ends up in the lock file with its latest version.

**Comment by metalmatze** [comment]
Do we really to put transitive deps in the lock file too? I mean we already pin the direct dependencies. So it would only be a cache in some way?

**Comment by metalmatze** [comment]
I think this is resolved now, is it?

**Comment by brancz** [comment]
It is, thanks for pointing out.
