### ISSUE TITLE
vendor directory structure like golang

### ISSUE THREAD

**Issue by hangxie** [jsonnet-bundler/jsonnet-bundler#61]
I'm curious that why jb does not do vendor directory like golang does, i.e. `vendor/github.com/anguslees/kustomize-libsonnet`? Then `import` can just do golang way like `import 'github.com/anguslees/kustomize-libsonnet/kustomize.libsonnet'` with help of `-J vendor` to guarantee uniqueness.

Or there is already a way to reach this? I tried to change `name` in jsonnetfile.json but it does not work.

**Comment by metalmatze** [comment]
Thanks for opening this issue. This is actually something that @brancz and I discussed not even a week ago again. From my perspective this would be something I'd really like! :blush:

**Comment by sh0rez** [comment]
That's cool! Especially because libraries are now **uniquely identified** at import time ... the source code is self-documentary for the location of the library

**Comment by brancz** [comment]
I think this would actually be pretty nice. I initially wanted to solve ambiguity with a registry but were far enough into it that I don’t think that that’s actually happening. I’d suggest we try this in a non breaking way first, where we just do the whole url if no package name is given and at some point just remove the whole thing.

**Comment by sh0rez** [comment]
maybe having an automatic rewrite tool as well would be handy .. should be fairly easy to grep for all imports of the old format, rewrite them to the new and change the `jsonnetfile.json`

**Comment by sh0rez** [comment]
How would this look on `local` packages?

**Comment by brancz** [comment]
I imagine it to work similar to go's canonical import paths. You specify the whole package name but then say it’s a local package and point at the directory you want it to use.

**Comment by brancz** [comment]
If anyone wants to give this a stab, ideally with keeping current imports working, I'd be happy to give it a review.

**Comment by sh0rez** [comment]
I'll draft an implementation over the weekend, let's see how far I get :D
