### ISSUE TITLE
jb fails to install dependency after PR #56

### ISSUE THREAD

**Issue by chancez** [jsonnet-bundler/jsonnet-bundler#62]
As far as I can tell, #56 broke `jb`, at least with some dependencies like https://github.com/ksonnet/ksonnet-lib/. 

On the latest master:

```
~/p/poetry czibolski ❯❯❯ jb install github.com/ksonnet/ksonnet-lib/ksonnet.beta.4/k.libsonnet
Cloning into 'vendor/.tmp/jsonnetpkg-k.libsonnet-master812140101'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 2505 (delta 0), reused 3 (delta 0), pack-reused 2500
Receiving objects: 100% (2505/2505), 2.48 MiB | 5.75 MiB/s, done.
Resolving deltas: 100% (933/933), done.
Already on 'master'
Your branch is up to date with 'origin/master'.
>>> Installed k.libsonnet version master
jb: error: failed to install: stat vendor/k.libsonnet/jsonnetfile.lock.json: not a directory
```

I mentioned this to @brancz in the k8s slack when I hit the issue and I looked at recent commits touching the area of code producing the error I see and checked out the commit before this (7fc7c31856f96b7215796e7126e6a5f3303b7214) and the issue is gone.

Running the same `jb install` as above using my locally build `jb` from commit 7fc7c31856f96b7215796e7126e6a5f3303b7214:
```
~/p/poetry czibolski ❯❯❯ /Users/czibolski/projects/jsonnet-bundler/_output/darwin/amd64/jb install github.com/ksonnet/ksonnet-lib/ksonnet.beta.4/k8s.libsonnet                                                   ⏎
GET https://github.com/ksonnet/ksonnet-lib/archive/0d2f82676817bbf9e4acf6495b2090205f323b9f.tar.gz 200
CLEAN vendor/k.libsonnet
```

_Originally posted by @chancez in https://github.com/jsonnet-bundler/jsonnet-bundler/pull/56#issuecomment-561872860_

**Comment by chancez** [comment]
Actually that doesn't seem to actually fix it cause the ksonnet files still aren't in `vendor` weirdly.

**Comment by davidovich** [comment]
I am investigating. It seems related to archive unpacking.

**Comment by davidovich** [comment]
You cannot install files in latest version, but directories. I believe this works:

```
make build
mkdir tmp
cd tmp
../_output/darwin/amd64/jb init
../_output/darwin/amd64/jb install github.com/ksonnet/ksonnet-lib/ksonnet.beta.4
```

**Comment by brancz** [comment]
That is correct, installing files only accidentally ever worked. For now install ksonnet-lib I would recommend.

**Comment by chancez** [comment]
Ahhh, okay thanks guys. I didn't realize that, but given the "bundler" in the name, I should know better. Everything works when I install the directories. Thanks again!

**Comment by brancz** [comment]
Sounds like we can close this?
