### ISSUE TITLE
Support other hosts than GitHub for https

### ISSUE THREAD

**Issue by cboggs** [jsonnet-bundler/jsonnet-bundler#72]
The introduction of the "absolute imports" feature broke the ability to use a generic (non-github) git repo as a package URI.

Given that we have private Gitlab repos that house dependencies for our projects, this is a blocker. :-)

I'll have a PR up for it shortly.

**Comment by sh0rez** [comment]
Hi, thanks for reporting.

Could you please explain how it broke exactly? 

Judging from the dependency parser, http on hosts other than github was not supported before:

https://github.com/jsonnet-bundler/jsonnet-bundler/blob/184841238bb5df1b886ccaecd3e179bc55c17687/cmd/jb/main.go#L36-L46

This snippet is from `v0.2.0`

**Comment by cboggs** [comment]
That's a great question actually, and I'm not super sure. All I know is that we currently pin `jb` to `v0.2.0` and it works with our internal Gitlab URLs, which is bizarre now that you mention it. :-\

**Comment by sh0rez** [comment]
Maybe somebody modified the jsonnetfile.json by hand? In that case, it is not unexpected to break.

Anyways, supporting all hosts is required anyways so yeah, I guess it is not broken, only unsupported

**Comment by davidovich** [comment]
We use gitlab references and I confirm that this is not supported at the moment, we modify the `jsonnetfile.json` by hand to use gitlab urls, which work. 

Supporting Gitlab would be great. But the last time I looked, I think that the path deducing code of the `install` command will not work well for the groups feature of gitlab (it is hardcoded to decude paths after `org/project` depth). I think that to support gitlab, we would need to modify the cli to accept a formal path parameter (instead of deducing from the github repo depth).

**Comment by sh0rez** [comment]
You might be right @davidovich. With the upcoming change by @cboggs we at least properly support gitlab urls at user/repo level.

Unsure about groups, we should add, probably in a future iteration.

**Comment by sc250024** [comment]
> Hi, thanks for reporting.
> 
> Could you please explain how it broke exactly?
> 
> Judging from the dependency parser, http on hosts other than github was not supported before:
> 
> https://github.com/jsonnet-bundler/jsonnet-bundler/blob/184841238bb5df1b886ccaecd3e179bc55c17687/cmd/jb/main.go#L36-L46
> 
> This snippet is from `v0.2.0`

I can tell you another problem with the `gitSSH` regex patterns: they don't account for GitLab's capability to add groups. For example, a GitHub repo is always `github.com/<org>/<repo>` whereas GitLab can have another subgroup like `gitlab.com/<org>/<group>/<repo>`

See here: https://docs.gitlab.com/ee/user/group/

I was just about to open an issue with "GitLab" support, which could just be adding another part to the regex with an optional third path for the `<org>/<group>/<repo>` format.

**Comment by sh0rez** [comment]
> I was just about to open an issue with "GitLab" support, which could just be adding another part to the regex with an optional third path for the `<org>/<group>/<repo>` format.

Unfortunately, it's not. From a regex perspective, there is no way to differentiate between:

```
gitlab.com/user/repo/sub/dir/foo
gitlab.com/group/user/repo/sub/dir
```

**Comment by hangxie** [comment]
> ```
> gitlab.com/user/repo/sub/dir/foo
> gitlab.com/group/user/repo/sub/dir
> ```

Never used gitlab group before, however, it seems both github and gitlab supports `/repo.git` in URL and will rewrite/redirect to `/repo`, will that be potential a solution? I'm not sure if this is just a hack.

**Comment by sh0rez** [comment]
This will require to do a http request during parsing, which I would like to avoid as it is slow
