### ISSUE TITLE
nil pointer error when refering to local git directory

### ISSUE THREAD

**Issue by pgier** [jsonnet-bundler/jsonnet-bundler#75]
I'm seeing a nil pointer error trying to run `jb install` using a file with a dependency pointing to a  local filesystem path.  It seems this use to work in 1.0, but is not working in 2.0 and master.
Example jsonnetfile.json
```json
{
    "dependencies": [
        {
            "name": "prometheus-operator",
            "source": {
                "git": {
                    "remote": "../../",
                    "subdir": "jsonnet/prometheus-operator"
                }
            },
            "version": "."
        }
    ]
}

```

Output:
```
cd scripts/generate; /home/pgier/go/bin/jb install;                                                                                                           
panic: runtime error: invalid memory address or nil pointer dereference                                                                                       
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5e21a1]                                                                                        
                                                                               
goroutine 1 [running]:                                                                                                                                        
github.com/jsonnet-bundler/jsonnet-bundler/spec/deps.(*Git).UnmarshalJSON(0xc0000f0280, 0xc000112afc, 0x77, 0x2b4, 0x7ffbb328f220, 0xc0000f0280)
        /home/pgier/go/src/github.com/jsonnet-bundler/jsonnet-bundler/spec/deps/git.go:71 +0xb1     
encoding/json.(*decodeState).object(0xc0000fa370, 0x7f6300, 0xc00012c000, 0x196, 0xc0000fa398, 0x7b)
```

**Comment by sh0rez** [comment]
AFAICT git repositories are only supported as long as they are remote, over `https` and `ssh`.

For local directories, consider using the `local` repository type instead:

```
$ jb install ../../jsonnet/prometheus-operator
```

**Comment by brancz** [comment]
Yes in 0.2 we have local packages and that’s what we should use in this situation. We used to do the above hack previously and it did used to work in 0.1 but we made sure that local packages are working before we removed this as this really only accidentally happened to work.

**Comment by metalmatze** [comment]
Yep. I guess this just needs updating on the Prometheus Operator side.

Something that I keep thinking about is and ever increasing uint version counter for jsonnetfile.json and lock too, so that we can at least tell people that they need a newer version. WDYT? (I know it's a bit off topic here, let me open a new issue in case we want that)

**Comment by sh0rez** [comment]
> Yep. I guess this just needs updating on the Prometheus Operator side.
> 
> Something that I keep thinking about is and ever increasing uint version counter for jsonnetfile.json and lock too, so that we can at least tell people that they need a newer version. WDYT? (I know it's a bit off topic here, let me open a new issue in case we want that)

Yeah I like that. In the last couple of weeks we have done a lot of changes to the jsonnetfile schema and I expect more to come in the future.

If jb would just be able to embed a schemaVersion and know which schemes it supports, that would be neat.

**Comment by brancz** [comment]
Yeah I think I like that as well.

**Comment by sh0rez** [comment]
Although this is basically working as intended, it should not panic, instead properly error.

Opened an issue for adding a schemaVersion: #76

**Comment by sh0rez** [comment]
We now have schema versions (#85), this should not happen anymore in the future.
