### ISSUE TITLE
CI flaking

### ISSUE THREAD

**Issue by sh0rez** [jsonnet-bundler/jsonnet-bundler#82]
Apparently we've got some flaking tests, tho I'm not sure why, as I can't reproduce locally (20 of 20 tries passed).

https://cloud.drone.io/jsonnet-bundler/jsonnet-bundler/123
https://cloud.drone.io/jsonnet-bundler/jsonnet-bundler/125

**Comment by metalmatze** [comment]
I've "fixed" those flaky tests in #85 by running the steps synchronous and not concurrently. This happens because some integration tests might be executed at the same time and then read and write to the same files in the same shared folder...

**Comment by sh0rez** [comment]
With #85 merged, this is resolved.
