### ISSUE TITLE
Granular update

### ISSUE THREAD

**Issue by brancz** [jsonnet-bundler/jsonnet-bundler#89]
We often want to update only one specific dependency, but what we end up having to do is run `jb update`, then `git add -p` and revert the rest, and make sure we didn't make a mistake. It would be much more convenient if this was built in.

@sh0rez @metalmatze

**Comment by sh0rez** [comment]
I think I don't quite get the use case .. could you explain it a bit further?

**Comment by brancz** [comment]
We often want to just update a single dependency like:

```
$ jb update github.com/kubernetes-monitoring/kubernetes-mixin@latest
```

But currently we can only do all via:

```
$ jb update
```

**Comment by sh0rez** [comment]
Actually you can use `jb install` for updating:

```bash
# some time ago
$ jb install github.com/kubernetes-monitoring/kubernetes-mixin
# ... installs master

# update it:-
jb install github.com/kubernetes-monitoring/kubernetes-mixin@abc12 # <- current master hash
jb install github.com/kubernetes-monitoring/kubernetes-mixin@master # <- still have master in jsonnetfile
```

That way that single dependency is updated. The `@hash` `@branch` dance is required because jb tries to be clever and does nothing if the URI and the one in the jsonnetfile match ... we could possibly add some logic here to not do this for branches.

**Comment by brancz** [comment]
Interesting, we haven't done that, you're right that mostly works. Thinking about it more, I feel running

```
$ jb update github.com/kubernetes-monitoring/kubernetes-mixin
```

Should update the pinned version to the "latest" of the floating version. What do you think? That shouldn't be all too difficult to implement.

**Comment by sh0rez** [comment]
Good idea! This also won't require us to do magic when trying to guess if `install` should update or not. 

I'll give it a shot!
