### ISSUE TITLE
Add `jb tidy` similar to `go modtidy` to remove unused dependencies

### ISSUE THREAD

**Issue by krasi-georgiev** [jsonnet-bundler/jsonnet-bundler#98]

**Comment by sh0rez** [comment]
This is tricky, because jb does no parsing of Jsonnet code, as it can't reliably detect what's imported, due to historical decisions (import style still in use).

However, it does keep `jsonnentfile.lock.json` clean, so it only ever installs what's needed by your direct dependencies in `jsonnetfile.json`.

**Comment by krasi-georgiev** [comment]
tricky as in out of scope or as in needs a lot of work but would be nice if someone can implement it?

**Comment by bgagnon** [comment]
> because jb does no parsing of Jsonnet code, as it can't reliably detect what's imported, due to historical decisions (import style still in use)

Well, we do have the `jb rewrite` command that reads and modifies Jsonnet code in place...

Jsonnet has a way to detect unused variables with `jsonnet-lint`, which could help as a first pass. Then, I wouldn't expect `jb` to be detect unused `import` results, but we could still cleanup `jsonnetfile.json` from any module not seen in any `import` directive.

As for `jsonnetfile.lock.json`, it's a little harder... basically you want to recursively tidy up the dependencies first before obtaining a minimal lockfile.

**Comment by metalmatze** [comment]
`jb rewrite` is pretty much a find and replace... 
It's far from really parsing jsonnet files and really trying to understand them.

I don't think this is an often enough use case for us to try and write a general-purpose tool. The false positives are too many.
Happy to be convinced of the opposite, but that's my stand on this topic for now.
